---Magnitude Analysis--
--Find total customers by country--
select country ,
count(customer_id)Total_customers 
from gold.dim_customers group by country 
order by Total_customers desc

--Find total customers by gender--
select gender ,
count(customer_id)Total_customers 
from gold.dim_customers group by gender
order by Total_customers desc


--Find total products by category--
select category,
count(product_key)Total_products
from gold.dim_products
Group by category
order by Total_products desc


--What is the avg cost in each category--
select category,avg(cost)avg_cost from gold.dim_products
group by category
order by avg_cost desc


--What is the total revenue generated for each category--
select  sum(fs.sales_amount)Total_revenue, 
dp.category from gold.fact_sales fs 
left join gold.dim_products dp on
fs.product_key = dp.product_key
group by dp.category
order by Total_revenue desc

--What is total revenue generated by each customers--
select fs.customer_key,dc.first_name,dc.last_name,sum(fs.sales_amount)Total_revenue from gold.fact_sales fs
left join gold.dim_customers dc on
fs.customer_key = dc.customer_key
group by fs.customer_key,
         dc.first_name,
         dc.last_name
order by Total_revenue desc


--What is the distribution of sold items cross countries--
select dc.country,count(quantity)Total_quantity from gold.fact_sales fs
left join gold.dim_customers dc on
fs.customer_key = dc.customer_key
left join gold.dim_products dp on
fs.product_key = dp.product_key
group by dc.country
order by Total_quantity desc
